# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: light.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blight.proto\x12\x05light\",\n\x05Light\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03rgb\x18\x02 \x01(\t\x12\n\n\x02on\x18\x03 \x01(\x08\"\x10\n\x02Id\x12\n\n\x02id\x18\x01 \x01(\r\"\x07\n\x05\x45mpty\"+\n\x0bLightStream\x12\x1c\n\x06lights\x18\x01 \x03(\x0b\x32\x0c.light.Light2\xeb\x01\n\x0cLightService\x12%\n\x08GetLight\x12\t.light.Id\x1a\x0c.light.Light\"\x00\x12(\n\x08SetLight\x12\x0c.light.Light\x1a\x0c.light.Light\"\x00\x12+\n\tGetLights\x12\x0c.light.Empty\x1a\x0c.light.Light\"\x00\x30\x01\x12+\n\tSetLights\x12\x0c.light.Light\x1a\x0c.light.Empty\"\x00(\x01\x12\x30\n\x0cSetGetLights\x12\x0c.light.Light\x1a\x0c.light.Light\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'light_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIGHT._serialized_start=22
  _LIGHT._serialized_end=66
  _ID._serialized_start=68
  _ID._serialized_end=84
  _EMPTY._serialized_start=86
  _EMPTY._serialized_end=93
  _LIGHTSTREAM._serialized_start=95
  _LIGHTSTREAM._serialized_end=138
  _LIGHTSERVICE._serialized_start=141
  _LIGHTSERVICE._serialized_end=376
# @@protoc_insertion_point(module_scope)
