# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x17\n\x06Number\x12\r\n\x05value\x18\x01 \x01(\x05\"&\n\nNumberList\x12\x18\n\x07numbers\x18\x01 \x03(\x0b\x32\x07.Number\"\x07\n\x05\x45mpty2l\n\rNumberService\x12\x1c\n\x06square\x12\x07.Number\x1a\x07.Number\"\x00\x12\x1d\n\x03sum\x12\x0b.NumberList\x1a\x07.Number\"\x00\x12\x1e\n\tsixtyNine\x12\x06.Empty\x1a\x07.Number\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NUMBER._serialized_start=14
  _NUMBER._serialized_end=37
  _NUMBERLIST._serialized_start=39
  _NUMBERLIST._serialized_end=77
  _EMPTY._serialized_start=79
  _EMPTY._serialized_end=86
  _NUMBERSERVICE._serialized_start=88
  _NUMBERSERVICE._serialized_end=196
# @@protoc_insertion_point(module_scope)
